site_name: "Elasticsearch 5.4 中文文档"
site_url: http://elasticsearch.apachecn.org
site_description: "Elasticsearch 5.4 中文文档"
site_author: ApacheCN Team

repo_url: https://github.com/apachecn/elasticsearch-doc-zh
repo_name: elasticsearch-doc-zh

use_directory_urls: true
nav:
- "Elasticsearch 5.4 中文文档" : "README.md"
- "Getting Started（入门指南）" : "0.md"
- "Basic Concepts（基础概念）" : "1.md"
- "Installation（安装）" : "2.md"
- "Exploring Your Cluster（探索集群）" : "3.md"
- "Cluster Health（集群健康）" : "4.md"
- "List All Indices（列出所有索引）" : "5.md"
- "Create an Index（创建索引）" : "6.md"
- "Index and Query a Document（索引和查询文档）" : "7.md"
- "Delete an Index（删除索引）" : "8.md"
- "Modifying Your Data（修改数据）" : "9.md"
- "Updating Documents（更新文档）" : "10.md"
- "Deleting Documents（删除文档）" : "11.md"
- "Batch Processing（批处理）" : "12.md"
- "Exploring Your Data（探索数据）" : "13.md"
- "The Search API（搜索 API）" : "14.md"
- "Introducing the Query Language（介绍查询语言）" : "15.md"
- "Executing Searches（执行查询）" : "16.md"
- "Executing Filters（执行过滤）" : "17.md"
- "Executing Aggregations（执行聚合）" : "18.md"
- "Conclusion（总结）" : "19.md"
- "Setup Elasticsearch（设置）" : "20.md"
- "Installing Elasticsearch（安装）" : "21.md"
- "zip 或 tar.gz 安装" : "22.md"
- "Debian软件包安装Elasticsearch" : "23.md"
- "用RPM安装Elasticsearch" : "24.md"
- "Windows 环境下安装ES" : "25.md"
- "Docker 方式安装" : "26.md"
- "配置Elasticsearch" : "27.md"
- "重要Elasticsearch配置" : "28.md"
- "安全配置" : "29.md"
- "启动前检查" : "30.md"
- "堆大小检查" : "31.md"
- "文件描述符检查" : "32.md"
- "内存锁定检查" : "33.md"
- "最大线程数检查" : "34.md"
- "最大虚拟内存检查" : "35.md"
- "最大map数检查" : "36.md"
- "JVM Client模式检查" : "37.md"
- "串行收集使用检查" : "38.md"
- "系统调用过滤检查" : "39.md"
- "OnError与OnOutOfMemoryError检查" : "40.md"
- "G1GC检查" : "41.md"
- "重要的系统配置" : "42.md"
- "系统设置" : "43.md"
- "在jvm.options中设置JVM堆大小" : "44.md"
- "禁用swapping" : "45.md"
- "文件描述符" : "46.md"
- "虚拟内存" : "47.md"
- "线程数" : "48.md"
- "升级Elasticsearch" : "49.md"
- "Elasticsearch停机" : "50.md"
- "重大改变" : "51.md"
- "在5.3 重大改变" : "52.md"
- "在5.2 重大改变" : "53.md"
- "Shadow Replicas已被弃用" : "54.md"
- "在5.1 重大改变" : "55.md"
- "在5.0 重大改变" : "56.md"
- "搜索和查询DSL改变" : "57.md"
- "映射改变" : "58.md"
- "过滤器改变" : "59.md"
- "Suggester变化" : "60.md"
- "索引API改变" : "61.md"
- "文档API改变" : "62.md"
- "设置的改变" : "63.md"
- "分配改变" : "64.md"
- "HTTP改变" : "65.md"
- "REST API改变" : "66.md"
- "CAT API改变" : "67.md"
- "Java API改变" : "68.md"
- "Packaging" : "69.md"
- "Plugin改变" : "70.md"
- "文件系统相关改变" : "71.md"
- "磁盘上数据的路径" : "72.md"
- "聚合改变" : "73.md"
- "脚本相关改变" : "74.md"
- "API 规范" : "75.md"
- "Multiple Indices（多个索引）" : "76.md"
- "Date math support in index names（索引名称对 Date 和 Math 的支持）" : "77.md"
- "常见选项" : "78.md"
- "URL-based access control（基于 URL 的访问控制）" : "79.md"
- "Document APIS" : "80.md"
- "Index API" : "81.md"
- "Get API" : "82.md"
- "Update API" : "83.md"
- "通过查询 API 更新" : "84.md"
- "多个 GET API" : "85.md"
- "Bulk API" : "86.md"
- "Reading and Writing documents（读写文档）" : "87.md"
- "Delete API" : "88.md"
- "Delete By Query API" : "89.md"
- "Reindex API" : "90.md"
- "Term Vectors" : "91.md"
- "Multi termvectors API" : "92.md"
- "?refresh" : "93.md"
- "Search APIs" : "94.md"
- "Search" : "95.md"
- "URI Search" : "96.md"
- "Request Body Search" : "97.md"
- "Query" : "98.md"
- "From / Size" : "99.md"
- "Sort" : "100.md"
- "Source filtering" : "101.md"
- "Fields" : "102.md"
- "Script Fields" : "103.md"
- "Doc value Fields" : "104.md"
- "Post filter" : "105.md"
- "Highlighting" : "106.md"
- "Rescoring" : "107.md"
- "Search Type" : "108.md"
- "Scroll" : "109.md"
- "Preference" : "110.md"
- "Explain" : "111.md"
- "Version" : "112.md"
- "Index Boost" : "113.md"
- "min_score" : "114.md"
- "Named Queries" : "115.md"
- "Inner hits" : "116.md"
- "Search After" : "117.md"
- "Field Collapsing 字段折叠" : "118.md"
- "Search 模板" : "119.md"
- "Multi Search 模板" : "120.md"
- "Search Shards API" : "121.md"
- "Suggesters" : "122.md"
- "Completion Suggester" : "123.md"
- "Context Suggester" : "124.md"
- "Phrase Suggester" : "125.md"
- "Term suggester" : "126.md"
- "Multi Search API" : "127.md"
- "Count API" : "128.md"
- "Validate API" : "129.md"
- "Explain API" : "130.md"
- "Profile API" : "131.md"
- "Profiling Queries" : "132.md"
- "Profiling Aggregations" : "133.md"
- "Profiling Considerations" : "134.md"
- "Aggregations" : "135.md"
- "Metric Aggregations" : "136.md"
- "值计数聚合（Value Count Aggregation）" : "137.md"
- "地理边界聚合" : "138.md"
- "地理重心聚合" : "139.md"
- "基数聚合" : "140.md"
- "平均值聚合" : "141.md"
- "扩展统计聚合" : "142.md"
- "最大值聚合" : "143.md"
- "最小值聚合" : "144.md"
- "Bucket Aggregations" : "145.md"
- "Children Aggregation" : "146.md"
- "Date Histogram Aggregation" : "147.md"
- "Date Range Aggregation" : "148.md"
- "Diversified Sampler Aggregation" : "149.md"
- "Filter Aggregation（过滤器聚合）" : "150.md"
- "Filters Aggregation" : "151.md"
- "Geo Distance Aggregation(地理距离聚合)" : "152.md"
- "GeoHash grid Aggregation(GeoHash网格聚合)" : "153.md"
- "Global Aggregation(全局聚合)" : "154.md"
- "Histogram Aggregation" : "155.md"
- "IP Range Aggregation(IP范围聚合)" : "156.md"
- "Missing Aggregation" : "157.md"
- "Nested Aggregation（嵌套聚合）" : "158.md"
- "Range Aggregation(范围聚合)" : "159.md"
- "Reverse nested Aggregation" : "160.md"
- "Sampler Aggregation" : "161.md"
- "Significant Terms Aggregation" : "162.md"
- "邻接矩阵聚合" : "163.md"
- "Pipeline Aggregations" : "164.md"
- "Avg Bucket Aggregation" : "165.md"
- "Derivative Aggregation（导数聚合）" : "166.md"
- "Max Bucket Aggregation" : "167.md"
- "Min Bucket Aggregation" : "168.md"
- "Sum Bucket Aggregation" : "169.md"
- "Stats Bucket Aggregation" : "170.md"
- "Extended Stats Bucket Aggregation（扩展信息桶聚合）" : "171.md"
- "Percentiles Bucket Aggregation（百分数桶聚合）" : "172.md"
- "Cumulative Sum Aggregation（累积汇总聚合）" : "173.md"
- "Bucket Script Aggregation（桶脚本聚合）" : "174.md"
- "Bucket Selector Aggregation（桶选择器聚合）" : "175.md"
- "Serial Differencing Aggregation（串行差异聚合）" : "176.md"
- "Matrix Aggregations" : "177.md"
- "Matrix Stats" : "178.md"
- "Matrix Stats（矩阵统计）" : "179.md"
- "Caching heavy aggregations（缓存频繁聚合）" : "180.md"
- "Returning only aggregation results（仅返回需要聚合的结果）" : "181.md"
- "Aggregation Metadata（聚合元数据）" : "182.md"
- "Returning the type of the aggregation（返回聚合的类型）" : "183.md"
- "索引 API" : "184.md"
- "Create Index /创建索引" : "185.md"
- "Delete Index /删除索引" : "186.md"
- "Get Index /获取索引" : "187.md"
- "Indices Exists /索引存在" : "188.md"
- "Open / Close Index API /启动关闭索引" : "189.md"
- "Shrink Index /缩小索引" : "190.md"
- "Rollover Index/滚动索引" : "191.md"
- "Put Mapping /提交映射" : "192.md"
- "Get Mapping /获取映射" : "193.md"
- "Get Field Mapping /获取字段映射" : "194.md"
- "卷影副本索引" : "195.md"
- "依赖卷影副本的节点级设置" : "196.md"
- "索引统计信息" : "197.md"
- "索引段" : "198.md"
- "索引恢复" : "199.md"
- "索引分片存储" : "200.md"
- "清理缓存" : "201.md"
- "刷新" : "202.md"
- "同步刷新" : "203.md"
- "重新加载" : "204.md"
- "强制合并" : "205.md"
- "cat APIs" : "206.md"
- "cat aliases" : "207.md"
- "cat allocation" : "208.md"
- "cat count" : "209.md"
- "cat fielddata" : "210.md"
- "cat health" : "211.md"
- "cat indices" : "212.md"
- "cat master" : "213.md"
- "cat nodeattrs" : "214.md"
- "cat nodes" : "215.md"
- "cat pending tasks" : "216.md"
- "cat plugins" : "217.md"
- "cat recovery" : "218.md"
- "cat repositories" : "219.md"
- "cat thread pool" : "220.md"
- "cat shards" : "221.md"
- "cat segments" : "222.md"
- "cat snapshots" : "223.md"
- "集群 API" : "224.md"
- "Cluster Allocation Explain API" : "225.md"
- "Cluster Health" : "226.md"
- "Cluster Reroute" : "227.md"
- "Cluster State" : "228.md"
- "Cluster Stats" : "229.md"
- "Cluster Update Settings" : "230.md"
- "Nodes hot_threads" : "231.md"
- "Nodes Info" : "232.md"
- "Nodes Stats" : "233.md"
- "Pending cluster tasks" : "234.md"
- "Task Management API" : "235.md"
- "查询 DSL" : "236.md"
- "查询和过滤上下文" : "237.md"
- "Match ALL 查询" : "238.md"
- "全文搜索" : "239.md"
- "匹配查询" : "240.md"
- "短语匹配查询" : "241.md"
- "短语前缀匹配查询" : "242.md"
- "多字段查询" : "243.md"
- "常用术语查询" : "244.md"
- "查询语句查询" : "245.md"
- "简单查询语句" : "246.md"
- "复合查询家族" : "247.md"
- "Constant Score 查询" : "248.md"
- "Bool 查询" : "249.md"
- "Dis Max 查询" : "250.md"
- "Function Score 查询" : "251.md"
- "Boosting 查询" : "252.md"
- "Indices 查询" : "253.md"
- "Join 查询" : "254.md"
- "Has Child Query" : "255.md"
- "Has Parent Query" : "256.md"
- "Nested Query(嵌套查询)" : "257.md"
- "Parent Id Query" : "258.md"
- "术语查询" : "259.md"
- "Exists Query(非空值查询)" : "260.md"
- "Fuzzy Query(模糊查询)" : "261.md"
- "Ids Query(ID 查询)" : "262.md"
- "Prefix Query(前缀查询)" : "263.md"
- "Range Query(范围查询)" : "264.md"
- "Regexp Query(正则表达式查询)" : "265.md"
- "Term Query(项查询)" : "266.md"
- "Terms Query(多项查询)" : "267.md"
- "Type Query(类型查询)" : "268.md"
- "Wildcard Query(通配符查询)" : "269.md"
- "地理位置查询" : "270.md"
- "GeoShape Query(地理形状查询)" : "271.md"
- "Geo Bounding Box Query（地理边框查询）" : "272.md"
- "Geo Distance Query（地理距离查询）" : "273.md"
- "Geo Distance Range Query（地理距离范围查询）" : "274.md"
- "Geo Polygon Query（地理多边形查询）" : "275.md"
- "Span 查询" : "276.md"
- "Span Term 查询" : "277.md"
- "Span Multi Term 查询" : "278.md"
- "Span First 查询" : "279.md"
- "Span Near 查询" : "280.md"
- "Span Or 查询" : "281.md"
- "Span Not 查询" : "282.md"
- "Span Containing 查询" : "283.md"
- "Span Within 查询" : "284.md"
- "Span Field Masking 查询" : "285.md"
- "Specialized queries(专业查询)" : "286.md"
- "Mapping(映射)" : "287.md"
- "字段类型" : "288.md"
- "Array" : "289.md"
- "Binary" : "290.md"
- "Range" : "291.md"
- "Boolean" : "292.md"
- "Date" : "293.md"
- "Geo-point datatype" : "294.md"
- "String" : "295.md"
- "Text" : "296.md"
- "Token数" : "297.md"
- "渗滤型" : "298.md"
- "KeyWord" : "299.md"
- "Nested" : "300.md"
- "Object" : "301.md"
- "Numeric" : "302.md"
- "Meta-Fields（元字段）" : "303.md"
- "_all field" : "304.md"
- "_field_names field" : "305.md"
- "_id field" : "306.md"
- "_index field" : "307.md"
- "_meta field" : "308.md"
- "_parent field" : "309.md"
- "_routing field" : "310.md"
- "_source field" : "311.md"
- "_type field" : "312.md"
- "_uid field" : "313.md"
- "Mapping parameters（映射参数）" : "314.md"
- "analyzer（分析器）" : "315.md"
- "normalizer(归一化)" : "316.md"
- "boost(提升)" : "317.md"
- "Coerce（强制类型转换）" : "318.md"
- "copy_to（合并参数）" : "319.md"
- "doc_values（文档值）" : "320.md"
- "dynamic（动态设置）" : "321.md"
- "enabled（开启字段）" : "322.md"
- "fielddata（字段数据）" : "323.md"
- "format （日期格式）" : "324.md"
- "ignore_above（忽略超越限制的字段）" : "325.md"
- "ignore_malformed（忽略格式不对的数据）" : "326.md"
- "include_in_all（_all 查询包含字段）" : "327.md"
- "index_options（索引设置）" : "328.md"
- "index （索引）" : "329.md"
- "fields（字段)" : "330.md"
- "Norms （标准信息）" : "331.md"
- "null_value（空值）" : "332.md"
- "position_increment_gap（短语位置间隙）" : "333.md"
- "properties （属性）" : "334.md"
- "search_analyzer （搜索分析器）" : "335.md"
- "similarity （匹配方法）" : "336.md"
- "store（存储）" : "337.md"
- "Term_vectors（词根信息）" : "338.md"
- "Dynamic Mapping（动态映射）" : "339.md"
- "_default_ mapping(mapping中的_default_)" : "340.md"
- "Dynamic field mapping(动态字段映射)" : "341.md"
- "Dynamic templates(动态模板)" : "342.md"
- "Override default template(覆盖默认模板)" : "343.md"
- "Mapping（映射）" : "344.md"
- "Analysis" : "345.md"
- "Tokenizers（分词器）" : "346.md"
- "Standard Tokenizer（标准分词器）" : "347.md"
- "Letter Tokenizer" : "348.md"
- "Lowercase Tokenizer (小写分词器)" : "349.md"
- "Whitespace Analyzer" : "350.md"
- "停止分析器" : "351.md"
- "UAX URL Email Tokenizer" : "352.md"
- "Classic Tokenizer" : "353.md"
- "Thai Tokenizer（泰语分词器）" : "354.md"
- "NGram Tokenizer" : "355.md"
- "Keyword Analyzer" : "356.md"
- "Path Hierarchy Tokenizer（路径层次分词器）" : "357.md"
- "Pattern Tokenizer" : "358.md"
- "Token Filters（词元过滤器）" : "359.md"
- "Apostrophe Token Filter(撇号/单引号过滤器)" : "360.md"
- "ASCII Folding Token Filter（ASCII Folding 词元过滤器）" : "361.md"
- "CJK Bigram Token Filter（CJK Bigram词元过滤器）" : "362.md"
- "CJK Width Token Filter（CJK宽度过滤器）" : "363.md"
- "Classic Token Filter(经典过滤器)" : "364.md"
- "Common Grams Token Filter(近义词词元过滤器)" : "365.md"
- "Compound Word Token Filter（复合词过滤器）" : "366.md"
- "Decimal Digit Token Filter(十进制数字过滤器)" : "367.md"
- "Delimited Payload Token Filter（Delimited Payload词元分析器）" : "368.md"
- "Edge NGram Token Filter（Edge NGram 词元过滤器）" : "369.md"
- "Elision Token Filter(Elision词元过滤器)" : "370.md"
- "Fingerprint Token Filter(指纹过滤器)" : "371.md"
- "Flatten Graph Token Filter（Flatten Graph 词元过滤器）" : "372.md"
- "Hunspell Token Filter(Hunspell 词元过滤器)" : "373.md"
- "Keep Types Token Filter（保留指定类型过滤器）" : "374.md"
- "Keep Words Token Filter(保留字过滤器)" : "375.md"
- "Keyword Marker Token Filter（Keyword Marker 词元过滤器）" : "376.md"
- "Keyword Repeat Token Filter（Keyword Repeat 词元过滤器）" : "377.md"
- "KStem Token Filter（KStem 词元过滤器）" : "378.md"
- "Length Token Filter（长度词元过滤器）" : "379.md"
- "Limit Token Count Token Filter(限制词元数量过滤器)" : "380.md"
- "Lowercase Token Filter（Lowercase 词元过滤器）" : "381.md"
- "Minhash Token Filter(Minhash过滤器)" : "382.md"
- "NGram Token Filter（NGram词元过滤器）" : "383.md"
- "Normalization Token Filter（标准化词元过滤器）" : "384.md"
- "Pattern Capture Token Filter(模式匹配词元过滤器)" : "385.md"
- "Pattern Replace Token Filter（模式替换词元过滤器）" : "386.md"
- "Phonetic Token Filter（Phonetic 词元过滤器）" : "387.md"
- "Porter Stem Token Filter（Porter Stem 词元过滤器）" : "388.md"
- "Reverse Token Filteredit(反向词元过滤器)" : "389.md"
- "Shingle Token Filter（Shingle 词元过滤器）" : "390.md"
- "Snowball Token Filter（Snowball 词元过滤器）" : "391.md"
- "Standard Token Filters（标准词元过滤器）" : "392.md"
- "Stemmer Override Token Filter（Stemmer Override 词元过滤器）" : "393.md"
- "Stemmer Token Filter（Stemmer 词元过滤器）" : "394.md"
- "Stop Token Filter（Stop 词元过滤器）" : "395.md"
- "Synonym Graph Token Filter（Synonym Graph 词元过滤器）" : "396.md"
- "Synonym Token Filter（Synonym 词元过滤器）" : "397.md"
- "Trim Token Filter(Trim词元过滤器)" : "398.md"
- "Truncate Token Filter（截断词元过滤器）" : "399.md"
- "Unique Token Filter（唯一词元过滤器）" : "400.md"
- "Uppercase Token Filter（Uppercase词元过滤器）" : "401.md"
- "Word Delimiter Token Filter（Word Delimiter 词元过滤器）" : "402.md"
- "Character Filters（字符过滤器）" : "403.md"
- "md Strip Character Filter" : "404.md"
- "Mapping Character Filter" : "405.md"
- "Pattern Replace Character Filter" : "406.md"
- "Anatomy of an analyzer（分析器的分析）" : "407.md"
- "Testing analyzers（测试分析器）" : "408.md"
- "Analyzers(分析器)" : "409.md"
- "Configuring built-in analyzers（配置内置分析器）" : "410.md"
- "Standard Analyzer（标准分析器）" : "411.md"
- "Simple Analyzer（简单分析器）" : "412.md"
- "空白分析器" : "413.md"
- "Stop Analyzer" : "414.md"
- "指纹分析器" : "415.md"
- "模式分析器" : "416.md"
- "自定义分析器" : "417.md"
- "语言分析器" : "418.md"
- "模块" : "419.md"
- "Indices（索引）" : "420.md"
- "Circuit breakers（熔断器）" : "421.md"
- "Fielddata cache(列数据缓存)" : "422.md"
- "indexing buffer(索引写入缓冲)" : "423.md"
- "indices Recovery(索引恢复)" : "424.md"
- "NetWork Setting(网络配置)" : "425.md"
- "Node Query Cache（节点查询缓存）" : "426.md"
- "Shard request cache(分片请求缓存)" : "427.md"
- "脚本" : "428.md"
- "Groovy 脚本语言" : "429.md"
- "Painless 脚本语言" : "430.md"
- "Painless 语法" : "431.md"
- "Painless 调试" : "432.md"
- "Lucene表达式语言" : "433.md"
- "原生（Java）脚本" : "434.md"
- "高级文本评分脚本" : "435.md"
- "快照和还原" : "436.md"
- "线程池" : "437.md"
- "传输" : "438.md"
- "HTTP" : "439.md"
- "Tribe Node (部落节点)" : "440.md"
- "跨集群搜索" : "441.md"
- "Cluster（集群）" : "442.md"
- "Disk-based Shard Allocation ( 基于磁盘的分片分配 )" : "443.md"
- "Shard Allocation Awareness ( 分片分配意识 )" : "444.md"
- "群集级别分片分配" : "445.md"
- "Node" : "446.md"
- "插件" : "447.md"
- "Index Modules（索引模块）" : "448.md"
- "Analysis（分析）" : "449.md"
- "索引分片分配" : "450.md"
- "分片分配过滤" : "451.md"
- "节点丢失时的延迟分配" : "452.md"
- "索引恢复的优先级" : "453.md"
- "每个节点的总分片数" : "454.md"
- "Mapper（映射）" : "455.md"
- "Merge（合并）" : "456.md"
- "Similarity module（相似模块）" : "457.md"
- "Slow log（慢日志）" : "458.md"
- "Store" : "459.md"
- "预加载数据到文件系统缓存" : "460.md"
- "Translog（事务日志）" : "461.md"
- "Ingest Node（预处理节点）" : "462.md"
- "Pipeline Definition（管道定义）" : "463.md"
- "Ingest APIs" : "464.md"
- "Put Pipeline API" : "465.md"
- "Get Pipeline API" : "466.md"
- "Delete Pipeline API" : "467.md"
- "Simulate Pipeline API（模拟管道 API）" : "468.md"
- "Accessing Data in Pipelines（访问管道中的数据）" : "469.md"
- "Handling Failures in Pipelines（处理管道中的故障）" : "470.md"
- "Processors（处理器）" : "471.md"
- "Append Processor（追加处理器）" : "472.md"
- "Convert Processor（转换处理器）" : "473.md"
- "Date Processor（日期处理器）" : "474.md"
- "Date Index Name Processor（日期索引名称处理器）" : "475.md"
- "Fail Processor（故障处理器）" : "476.md"
- "Foreach Processor（循环处理器）" : "477.md"
- "Grok Processor（Grok 处理器）" : "478.md"
- "Gsub Processor（Gsub 处理器）" : "479.md"
- "Join Processor（连接处理器）" : "480.md"
- "JSON Processor（JSON 处理器）" : "481.md"
- "KV Processor（KV 处理器）" : "482.md"
- "Lowercase Processor（小写处理器）" : "483.md"
- "Remove Processor（删除处理器）" : "484.md"
- "Rename Processor（重命名处理器）" : "485.md"
- "Script Processor（脚本处理器）" : "486.md"
- "Set Processor（设置处理器）" : "487.md"
- "Split Processor（拆分处理器）" : "488.md"
- "Sort Processor（排序处理器）" : "489.md"
- "Trim Processor（修剪处理器）" : "490.md"
- "Uppercase Processor（大写处理器）" : "491.md"
- "Dot Expander Processor（点扩展器处理器）" : "492.md"
- "How to（操作方式）" : "493.md"
- "一些建议" : "494.md"
- "Recipes（诀窍）" : "495.md"
- "索引速率调优" : "496.md"
- "查询优化" : "497.md"
- "磁盘使用调优" : "498.md"
- "Testing（测试）" : "499.md"
- "Java Testing Framework（测试框架）" : "500.md"
- "( why randomized testing ) 为什么随机测试？" : "501.md"
- "Using the elasticsearch test classes ( 使用 elasticsearch 测试类 )" : "502.md"
- "unit tests（单元测试）" : "503.md"
- "integreation test（集成测试）" : "504.md"
- "Randomized testing（随机测试）" : "505.md"
- "Assertions（）" : "506.md"
- "Glossary of terms (词汇表)" : "507.md"
- "Release Notes（版本说明）" : "508.md"
- "5.3.0 版本说明" : "509.md"
- "5.2.2 Release Notes" : "510.md"
- "5.2.1 Release Notes" : "511.md"
- "5.2.0 Release Notes" : "512.md"
- "5.1.2 Release Notes" : "513.md"
- "5.1.1 Release Notes" : "514.md"
- "5.1.0 Release Notes" : "515.md"
- "5.0.1 Release Notes" : "516.md"

theme:
  name: mkdocs
  custom_dir: 'custom_theme/'
  
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: 'zh'
  feature:
    tabs: false
  palette:
    primary: 'Teal'
    accent: 'Teal'
  font: false
  favicon: assets/images/favicon.png
  logo: 
    icon: "\uE80C"